server:
  port: 5003

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:7050/eureka"
  instances:
    leaseRenewalIntervalInSeconds: 10
spring:
  data:
    elasticsearch:
      repositories: 'enabled'
      cluster-name: 'docker-cluster'
      cluster-nodes: 'localhost:9300'
  jpa:
    show-sql: 'true'

#logging:
#  level:
#    org:
#      hibernate:
#        tool:
#          hbm2ddl: true
#        sql: 'DEBUG'
#